name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: /server
    environment:
      - LOGGING_LEVEL=DEBUG
      - SERVER_PORT=8080
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - CLI_SERVER_ADDRESS=server:8080
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
